# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", 'tables', "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
sass:
  style: expanded
# Site settings
title: "tkssharma.io"
tagline: "Learn practical web skills"
description: "The website from tarun sharma, helping improve lives by teaching front-end web skills with a clear, practical style."
email: tarun.softengg@gmail.com
twitteruser: "@tkssaharma"
logo: "/assets/images/powship.png" #blog logo
cover: "/assets/images/hero.jpg" # blog cover

author:
  firstname: "Tarun"
  name: "Tarun Sharma"
  bio: "Tarun Sharma is developer published and trainer to provide training to javascript and java developers"

author_image: "/assets/images/author.jpg"
ldcjsonfeed: http://planetoftheweb.com/i/courses.php?author=832401&limit=0&filter.includes=Title,ShortDescription,DurationInSeconds,URLs,ID,WelcomeVideoId,Thumbnails.filename

paginate:	20

url: "http://kumartarun.github.io" # the base hostname & protocol for your site

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tkssharma
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url:  https://facebook.com/viewsource
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: linkedin
    url:  https://in.linkedin.com/in/tarun-sharma-03790254
    desc: Connect with me on LinkedIn

  - icon:	github
    url:	https://github.com/tkssharma
    desc:	Fork me on github

  - icon:	google-plus
    url:	https://plus.google.com/107471860931223719295/
    desc:	Add me on google+

  - icon:	dribbble
    url:	#
    desc:	Follow me on dribbble

  - icon:	flickr
    url:	#
    desc:	My flickr portfolio

  - icon:	youtube
    url:	https://www.youtube.com/user/vibbbbbba/playlists
    desc:	Subscribe to my youtube channel
